version: '3'

services:
  mongodb:
    image: "mongo:3.2"
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on: 
      - mongodb

  client:
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server